### ISSUE TITLE
npm ERR! 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129

### ISSUE THREAD

**Issue by matthewwren** [NativeScript/playground-feedback#190]
I installed the latest version of Node and then ran:

`npm install -g nativescript@latest`

I downloaded an unmodified Angular sample from playground, unzipped it and then ran in the app directory:

`tns preview`

I get the following output and error:

```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
npm ERR! 404
npm ERR! 404  'pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'kinvey-nativescript-sdk'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matth\AppData\Roaming\npm-cache\_logs\2020-08-08T17_04_58_821Z-debug.log
Command npm.cmd failed with exit code 1

```

The tail end of the log file is as follows:

```
2247 silly saveTree +-- rxjs@6.5.4
2247 silly saveTree +-- tns-core-modules@6.5.0
2247 silly saveTree `-- zone.js@0.10.2
2248 verbose stack Error: 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
2248 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:114:15
2248 verbose stack     at runMicrotasks (<anonymous>)
2248 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2249 verbose statusCode 404
2250 verbose pkgid pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
2251 verbose cwd C:\Users\matth\projects\ns-playground
2252 verbose Windows_NT 10.0.18363
2253 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2254 verbose node v12.18.3
2255 verbose npm  v6.14.6
2256 error code E404
2257 error 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
2258 error 404
2259 error 404 'pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129' is not in the npm registry.
2260 error 404 You should bug the author to publish it (or use the name yourself!)
2261 error 404 It was specified as a dependency of 'kinvey-nativescript-sdk'
2262 error 404 Note that you can also install from a
2263 error 404 tarball, folder, http url, or git url.
2264 verbose exit [ 1, true ]
```

I am running on Windows 10.

**Comment by verdulife** [comment]
> I installed the latest version of Node and then ran:
> 
> `npm install -g nativescript@latest`
> 
> I downloaded an unmodified Angular sample from playground, unzipped it and then ran in the app directory:
> 
> `tns preview`
> 
> I get the following output and error:
> 
> ```
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
> npm ERR! 404
> npm ERR! 404  'pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'kinvey-nativescript-sdk'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\matth\AppData\Roaming\npm-cache\_logs\2020-08-08T17_04_58_821Z-debug.log
> Command npm.cmd failed with exit code 1
> ```
> 
> The tail end of the log file is as follows:
> 
> ```
> 2247 silly saveTree +-- rxjs@6.5.4
> 2247 silly saveTree +-- tns-core-modules@6.5.0
> 2247 silly saveTree `-- zone.js@0.10.2
> 2248 verbose stack Error: 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
> 2248 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:114:15
> 2248 verbose stack     at runMicrotasks (<anonymous>)
> 2248 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 2249 verbose statusCode 404
> 2250 verbose pkgid pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
> 2251 verbose cwd C:\Users\matth\projects\ns-playground
> 2252 verbose Windows_NT 10.0.18363
> 2253 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 2254 verbose node v12.18.3
> 2255 verbose npm  v6.14.6
> 2256 error code E404
> 2257 error 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129
> 2258 error 404
> 2259 error 404 'pubnub@https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129' is not in the npm registry.
> 2260 error 404 You should bug the author to publish it (or use the name yourself!)
> 2261 error 404 It was specified as a dependency of 'kinvey-nativescript-sdk'
> 2262 error 404 Note that you can also install from a
> 2263 error 404 tarball, folder, http url, or git url.
> 2264 verbose exit [ 1, true ]
> ```
> 
> I am running on Windows 10.

Same here 😢

**Comment by KaleoBraghini** [comment]
Same here!

**Comment by therosko** [comment]
Unfortunately, I am experiencing the same issue. Has anyone found a solution for it in the mean time? :/

**Comment by maximbaran** [comment]
Same issue. Has anyone found a solution?

**Comment by duyendotnguyen** [comment]
I'm also having the same issue - am trying to run the Vue tutorial on OS X.

**Comment by therosko** [comment]
Hi all, 

I found one approach so far! 
Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ). 
To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being. 

Hope that works for you, too!

**Comment by matthewwren** [comment]
> Hi all,
> 
> I found one approach so far!
> Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ).
> To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.
> 
> Hope that works for you, too!

Works for me.  Thanks @therosko

**Comment by SreekanthJos** [comment]
Worked for me 

> Hi all,
> 
> I found one approach so far!
> Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ).
> To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.
> 
> Hope that works for you, too!

This solution worked for me 👍

**Comment by EricClevy** [comment]
this fix changed EVERYTHING !  Thanks for person who solved this error

**Comment by gonzaloabruna** [comment]
> Hi all,
> 
> I found one approach so far!
> Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ).
> To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.
> 
> Hope that works for you, too!

Indeed, this worked for me too, thanks @therosko !!

**Comment by EricClevy** [comment]
Yes, this fix worked for me as well .
Thanks again

De : gonzaloabruna <notifications@github.com>
Envoyé : lundi 14 septembre 2020 23:21
À : NativeScript/playground-feedback <playground-feedback@noreply.github.com>
Cc : Eric Clevy <eric.clevy@cohu.com>; Comment <comment@noreply.github.com>
Objet : Re: [NativeScript/playground-feedback] npm ERR! 404 Not Found - GET https://github.com/thomasconner/javascript/tarball/67b7944366453a87226389d483ac1ad861e0e129 (#190)


Caution:  This message originated externally. Please use caution when clicking on links or opening attachments! If this email looks suspicious do not reply or forward.



Hi all,

I found one approach so far!
Try changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json ( "kinvey-nativescript-sdk": "5.0.0" ).
To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.

Hope that works for you, too!

Indeed, this worked for me too, thanks @therosko<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftherosko&data=02%7C01%7Ceric.clevy%40cohu.com%7C1c73bc0bd35e4ed6b66008d858f40bfb%7Ceacc2a35149847488d1f03fb953672f8%7C0%7C0%7C637357153151964144&sdata=gIYuKdPlsIcOCG2IrLGOlQuwYXbThqZDMmDmm8bgWBo%3D&reserved=0> !!

**Comment by kidaqrus** [comment]
thanks it worked

**Comment by javavega7** [comment]
It worked for me!

**Comment by SoYoureAWaffleMan** [comment]
Playground / Preview are a great experience - https://play.nativescript.org/ prompts you to run `tns preview` when you d/l the source then the process breaks on a 404 and it's been an issue since August. I don't get it.

Is there a disparity between NS-cli builds and NS Playground builds or is the latter just out of date? If the local build falls over then I guess I have to stop using Playground & rewrite my app locally.

**Comment by therosko** [comment]
> Playground / Preview are a great experience - https://play.nativescript.org/ prompts you to run `tns preview` when you d/l the source then the process breaks on a 404 and it's been an issue since August. I don't get it.
> 
> Is there a disparity between NS-cli builds and NS Playground builds or is the latter just out of date? If the local build falls over then I guess I have to stop using Playground & rewrite my app locally.

I ran into quite a lot of issues with Playground / Preview and due to deadlines, decided to switch to a devcontainer. It ended up working really well and does the same job + you have the code locally. I have been postponing it for a while, but after I read your post today, I published the project on my profile just now. I hope it helps you or someone else, who might be struggling with the issues since mid August.
(hope this suggestion does not go against some policies... newbie here...)

**Comment by MuhaiminS** [comment]
> Hi all,
> 
> I found one approach so far!
> Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ).
> To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.
> 
> Hope that works for you, too!

It's working for me also.. Thanks..

**Comment by christianpadovano** [comment]
execuse me , after this 
Try changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json ( "kinvey-nativescript-sdk": "5.0.0" ).

i've a new error : 

ERROR in The target entry-point "listview-directives" has missing dependencies:
 - nativescript-angular/element-registry
 - nativescript-angular/renderer
 - ./../
 - tns-core-modules/ui/layouts/layout-base
 - tns-core-modules/data/observable-array
 - tns-core-modules/ui/core/view
 - tns-core-modules/data/observable
 - tns-core-modules/color
 - tns-core-modules/ui/layouts/stack-layout

Executing webpack failed with exit code 2.

and now ???

Is it possible that after a framework update all the old release become useless ?????

**Comment by athirarenjan** [comment]
> Hi all,
> 
> I found one approach so far!
> Try **changing the version of kinvey-nativescript-sdk to 5.0.0 in package.json** ( `"kinvey-nativescript-sdk": "5.0.0"` ).
> To me it looks good so far, meaning that I have not stumbled upon any other issues for the time being.
> 
> Hope that works for you, too!

Works for me

**Comment by dkprgs** [comment]
Hi guys,

I have the same issue.
However when changing the version of kinvey-nativescript-sdk it seems that other issues are triggered.
Is there a way to maintain my current version of the SDK ? "kinvey-nativescript-sdk": "4.2.1"
