### ISSUE TITLE
Issue when IMPORT module and component on Android 7.1.2

### ISSUE THREAD

**Issue by ikhsanuddin** [NativeScript/playground-feedback#45]
### Did you search for the problem in [other open issues in this repo](https://github.com/NativeScript/playground-feedback/issues)?
Yes, nothing related

### Tell us about the problem
I have some problem when using {N} Playground with android 7.1.2 

I'm currently developing apps using android and iphone,
with my code, it's works perfectly on iphone. but not with my android. 

issue found when i'm using _import_ for module and component.

### Did you try it outside of {N} Playground?
- Yes - Using **tns build**, its okay to run on android. but when it's using playground.

### Which browser are you using?
- Chrome

### Are there any errors/warnings logged in your browser console?
_main.f0de293b4dc5312b4c98.js:1_ 

ERROR Error: Uncaught (in promise): [object Undefined]
    at O (polyfills.5b26b48293db65525674.js:1)
    at polyfills.5b26b48293db65525674.js:1
    at main.f0de293b4dc5312b4c98.js:1
    at v (scripts.09bc68f12cb9dbaefd0b.js:1)
    at scripts.09bc68f12cb9dbaefd0b.js:1
    at a.callback (scripts.09bc68f12cb9dbaefd0b.js:1)
    at a.crossDomainError (scripts.09bc68f12cb9dbaefd0b.js:1)
    at XMLHttpRequest.e.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (scripts.09bc68f12cb9dbaefd0b.js:1)
    at XMLHttpRequest.F (polyfills.5b26b48293db65525674.js:1)
    at t.invokeTask (polyfills.5b26b48293db65525674.js:1)

### Which platform(s) does your issue occur on?
- Android

### Are there any entries logged in the Device Logs tab?

[Xiaomi Redmi 5 Plus]: An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'create' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 75, column: 14

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 75, column: 15
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 118, column: 30
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 818, column: 30
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2802)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6379)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'create' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js, line: 75, column: 14

StackTrace: 
Frame: function:'', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/builder/builder.js', line: 75, column: 15
Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 118, column: 30
Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 818, column: 30
Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 677, column: 14
Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
at com.tns.Runtime.callJSMethod(Runtime.java:970)
at com.tns.Runtime.callJSMethod(Runtime.java:954)
at com.tns.Runtime.callJSMethod(Runtime.java:946)
at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
at android.app.Activity.performCreate(Activity.java:6875)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2694)
... 9 more
[Xiaomi Redmi 5 Plus]: com.tns.NativeScriptException: 

Cannot compile /data/data/org.nativescript.preview/files/app/app.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.preview/files/app/app.js, line: 2, column: 7

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266

SyntaxError: Unexpected identifier
File: ", line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:542)
at com.tns.Runtime.run(Runtime.java:534)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5542)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6379)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

### Please provide the following information shown in devices tab in the playground:
- XIAOMI Redmi 5 Plus
- OS Ver (7.1.2)
- Preview app version (1.13.0)
- Runtime version (4.1.2)

### Please tell us how to recreate the issue with as much detail as possible.
I'm reconstruct nativescript build with vue-cli into playground.
he my project link [https://play.nativescript.org/?template=play-vue&id=NTgQCU&v=21]( https://play.nativescript.org/?template=play-vue&id=NTgQCU&v=21).

**Comment by darind** [comment]
@ikhsanuddin, I can see a couple of issues with this particular session. You seem to have added `tns-core-modules` as NPM package in the Playground which is not needed because the {N} modules are already part of the Preview app and can be used globally. 

If you download the project from the Playground and try to build it locally with the CLI, the android static binding generator will complain about duplicate classes because of that. Once you remove the `./tns-core-modules` folder you will be able to build the project locally.

Unfortunately at runtime the app will crash with the same exception (`tns run android` command).  This is a strong indication that this particular problem is not related to the Playground.

Please feel free to reopen this issue if you find some specific problem with the {N} Playground.
