### ISSUE TITLE
VueJS playground apps crash when trying to launch directly from mobile

### ISSUE THREAD

**Issue by shiv19** [NativeScript/playground-feedback#69]
Steps to reproduce:
1. create a simple vue js app and save it.

2 .open the link directly from mobile and click view saved project.

result: The app crashes.

expected: It should let you view the saved project. (just like the way you can for other flavors of {N})

```com.tns.NativeScriptException:

Cannot compile /data/data/org.nativescript.preview/files/app/app.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.preview/files/app/app.js, line: 1, column: 67

StackTrace: 
    Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'require', file:'', line: 1, column: 266


    at com.tns.Runtime.runModule(Native Method)
    at com.tns.Runtime.runModule(Runtime.java:553)
    at com.tns.Runtime.run(Runtime.java:545)
    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
    at android.app.ActivityThread.-wrap3(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Native Method)```

It seems like webpack is not compiling the vue files.

It is also worth noting that the link from mobile is `nsplay://boot?pKey=pub-c-...&sKey=sub-c-...&template=play-vue&sessionId=...` while the qr code is `nsplay://boot?instanceId=...&pKey=pub-c-...&sKey=sub-c-...&template=play-vue`.

**Comment by darind** [comment]
@shiv19, we are aware of this issue and a fix is already undergoing testing on our staging environment. Will report here once it ships to the LIVE environment. Unfortunately all SFC sessions that have been saved prior to this fix will not work and might require another revision.

**Comment by vhristov5555** [comment]
We have deployed a fix for the problem.

**Comment by Bilal-S** [comment]
Still occuring. 
Exact issue.

```
Cannot compile /data/data/org.nativescript.preview/files/app/app.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.preview/files/app/app.js, line: 1, column: 67

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266


        at com.tns.Runtime.runModule(Native Method)
        at com.tns.Runtime.runModule(Runtime.java:553)
        at com.tns.Runtime.run(Runtime.java:545)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```

**Comment by moogacs** [comment]
@vhristov5555  still occurring

**Comment by mbokil** [comment]
I just downloaded Playground for iOS. Scanned my QR code and the app dies instantly. Exception: 

```
CONSOLE INFO file:///app/vendor.js:145:32: HMR: Hot Module Replacement Enabled. Waiting for signal.
2019-09-03 15:33:14.752 nsplaydev[5406:1162740] ***** Fatal JavaScript exception - application has been terminated. *****
2019-09-03 15:33:14.752 nsplaydev[5406:1162740] Native stack trace:
1   0x100892048 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1008d2028 -[TNSRuntime executeModule:referredBy:]
3   0x101a2db14 -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4   0x100233428
5   0x1b70ab3f4 <redacted>
2019-09-03 15:33:14.752 nsplaydev[5406:1162740] JavaScript stack trace:
2019-09-03 15:33:14.752 nsplaydev[5406:1162740] 1   @file:///app/bundle.js:315:13
2   ./main.js@file:///app/bundle.js:321:34
3   __webpack_require__@file:///app/runtime.js:751:34
4   checkDeferredModules@file:///app/runtime.js:44:42
5   webpackJsonpCallback@file:///app/runtime.js:31:39
6   anonymous@file:///app/bundle.js:2:61
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
2019-09-03 15:33:14.752 nsplaydev[5406:1162740] JavaScript error:
file:///app/bundle.js:315:13: JS ERROR ReferenceError: Can't find variable: store
2019-09-03 15:33:14.753 nsplaydev[5406:1162740] PlayLiveSync: Uncaught Exception
2019-09-03 15:33:14.753 nsplaydev[5406:1162740] *** JavaScript call stack:
(

)
2019-09-03 15:33:14.753 nsplaydev[5406:1162740] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: store
 at 
1   @file:///app/bundle.js:315:13
2   ./main.js@file:///app/bundle.js:321:34
3   __webpack_require__@file:///app/runtime.js:751:34
4   checkDeferredModules@file:///app/runtime.js:44:42
5   webpackJsonpCallback@file:///app/runtime.js:31:39
6   anonymous@file:///app/bundle.js:2:61
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1b72a8b64 0x1b6fd10a4 0x10089248c 0x1008d2028 0x101a2db14 0x100233428 0x1b70ab3f4)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-09-03 15:33:14.753 nsplaydev[5406:1162740] PlayLiveSync: Uncaught Exception
```

**Comment by pascualstromsnes** [comment]
I can confirm that I was able to reproduce what @mbokil has described above.

### Steps to reproduce
1. Created a fresh installation with `vue init nativescript-vue/vue-cli-template voed-app`
2. Ran `npm install`
3. Ran `tns preview` and scanned the QR code from the Playgroud iOS app.
4. The app crashed immediately with the following console info:
```
`Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (ios)
Start sending initial files for platform ios.
Successfully sent initial files for platform ios.
LOG from device Pascual sin iPhone: CONSOLE INFO file:///app/vendor.js:145:32: HMR: Hot Module Replacement Enabled. Waiting for signal.
2019-09-08 18:49:56.794 nsplaydev[10574:2049301] ***** Fatal JavaScript exception - application has been terminated. *****
2019-09-08 18:49:56.794 nsplaydev[10574:2049301] Native stack trace:
1   0x1058072fc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10584c2a4 -[TNSRuntime executeModule:referredBy:]
3   0x1067f21f8 -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4   0x104ecf420
5   0x2286468e0 <redacted>
2019-09-08 18:49:56.799 nsplaydev[10574:2049301] JavaScript stack trace:
2019-09-08 18:49:56.799 nsplaydev[10574:2049301] file:///app/bundle.js:315:13
at ./main.js(file:///app/bundle.js:321:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
2019-09-08 18:49:56.799 nsplaydev[10574:2049301] JavaScript error:
file:///app/bundle.js:315:13: JS ERROR ReferenceError: Can't find variable: store
2019-09-08 18:49:56.802 nsplaydev[10574:2049301] PlayLiveSync: Uncaught Exception
2019-09-08 18:49:56.805 nsplaydev[10574:2049301] *** JavaScript call stack:
(

)
2019-09-08 18:49:56.805 nsplaydev[10574:2049301] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: store
 at 
file:///app/bundle.js:315:13
at ./main.js(file:///app/bundle.js:321:34)
at __webpack_require__(file:///app/runtime.js:751:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x228bf698c 0x227dcf9f8 0x105807778 0x10584c2a4 0x1067f21f8 0x104ecf420 0x2286468e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-09-08 18:49:56.805 nsplaydev[10574:2049301] PlayLiveSync: Uncaught Exception`
```

I have also tried running `tns run ios`.
This also results in an immediate crash and yields the following console output:

```
`CONSOLE INFO file:///node_modules/nativescript-dev-webpack/hot.js:3:23 HMR: Hot Module Replacement Enabled. Waiting for signal.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10116091f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1011a6d1f -[TNSRuntime executeModule:referredBy:]
3   0x100b9ccc3 main
4   0x104a88541 start
JavaScript stack trace:
1   @file:///app/bundle.js:315:13
2   ./main.js@file:///app/bundle.js:321:34
3   __webpack_require__@file:///app/webpack/bootstrap:750:0
4   checkDeferredModules@file:///app/webpack/bootstrap:43:0
5   webpackJsonpCallback@file:///app/webpack/bootstrap:30:0
6   anonymous@file:///app/bundle.js:2:61
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
JavaScript error:
file:///app/bundle.js:315:13: JS ERROR ReferenceError: Can't find variable: store
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: store
at
1   @file:///app/bundle.js:315:13
2   ./main.js@file:///app/bundle.js:321:34
3   __webpack_require__@file:///app/webpack/bootstrap:750:0
4   checkDeferredModules@file:///app/webpack/bootstrap:43:0
5   webpackJsonpCallback@file:///app/webpack/bootstrap:30:0
6   anonymous@file:///app/bundle.js:2:61
7   evaluate@[native code]
8   moduleEvaluation@[native code]
9   promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001044d28db __exceptionPreprocess + 331
1   libobjc.A.dylib                     0x0000000103326ac5 objc_exception_throw + 48
2   NativeScript                        0x0000000101160d58 _ZN12NativeScript30reportFatalErrorBeforeShutdownEPN3JSC9ExecStateEPNS0_9ExceptionEb + 1336
3   NativeScript                        0x00000001011a6d1f -[TNSRuntime executeModule:referredBy:] + 671
4   voedapp       <…>
NativeScript caught signal 6.
Native Stack:
1   0x1011a584f sig_handler(int)
2   0x104decb5d _sigtramp
3   0x1010d4270
4   0x104b6f01d abort
5   0x1049039d1 __cxa_bad_cast
6   0x104903b6f default_unexpected_handler()
7   0x103326e2d _objc_terminate()
8   0x10490fa2e std::__terminate(void (*)())
9   0x10490f4eb __cxa_get_exception_ptr
10  0x10490f4b2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x103326bfa _objc_exception_destructor(void*)
12  0x101160d58 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x1011a6d1f -[TNSRuntime executeModule:referredBy:]
14  0x100b9ccc3 main
15  0x104a88541 start
JS Stack:`
```

### Possible resolution
The key information from the console output here, as far as I can see, is the mention of an undefined variable named **_store_**.
When running tns preview
`JavaScript error:
file:///app/bundle.js:315:13: JS ERROR ReferenceError: Can't find variable: store`

When running tns run ios

`JavaScript error:
file:///app/bundle.js:315:13: JS ERROR ReferenceError: Can't find variable: store`

When creating this fresh app I opted in to use the vuex store.
Examining the main.js generated by the cli tool, I do find an undefined use of _**store**_:

```javascript
import Vue from 'nativescript-vue'
import App from './components/App'

  
// Prints Vue logs when --env.production is *NOT* set while building
Vue.config.silent = (TNS_ENV === 'production')

new Vue({
  store,
  render: h => h('frame', [h(App)])
}).$start()
```

Commenting out line 10 in main.js makes the app run fine with both tns run ios and tns preview.
Seeing that this most likely isn't an issue related to Playground itself, perhaps it should be moved?
